# Configuration file for object detection testing

# Model settings
model_path: "./checkpoints/best_model.pt"
num_runs: 5  # Number of test iterations

# Metrics configuration
metrics:
  iou_thresholds: [0.5, 0.75]
  confidence_threshold: 0.5
  size_ranges:
    small: [0, 1024]      # 32x32
    medium: [1024, 9216]  # 32x32 to 96x96
    large: [9216, null]   # > 96x96

# Data configuration
data:
  test_dir: "data/test"
  test_annotations: "annotations/test.json"
  batch_size: 1
  num_workers: 0
  pin_memory: false
  persistent_workers: false

# Visualization settings
visualization:
  confidence_threshold: 0.5
  pred_box_color: "red"
  gt_box_color: "blue"
  box_width: 2
  figure_size: [10, 6]
  dpi: 100
  save_visualizations: true

# Output configuration
output:
  results_dir: "./paper_results"
  test_results_dir: "./test_results"
  save_individual_results: true
  save_aggregate_results: true
  save_visualizations: true