# Configuration file for transfer learning

transfer:
  # Path to your pretrained model
  pretrained_model_path: "best_model.pt"
  
  # Layer freezing settings
  freeze_backbone: true    # Freeze the backbone network
  freeze_rpn: false       # Don't freeze RPN (allow it to adapt)
  freeze_roi_heads: false # Don't freeze ROI heads (allow it to adapt)
  
  # Learning rates for fine-tuning
  learning_rates:
    backbone: 0.0001  # Very low learning rate for backbone if not frozen
    rpn: 0.001       # Higher learning rate for RPN
    roi_heads: 0.001 # Higher learning rate for ROI heads
    
  # Training settings
  training:
    epochs: 50       # Number of epochs for fine-tuning
    batch_size: 1    # Batch size
    initial_epoch: 0 # Start epoch number

# Model configuration (same as base config)
model:
  num_classes: 2  
  min_size: 800
  max_size: 1333
  box_score_thresh: 0.05
  box_nms_thresh: 0.4
  box_detections_per_img: 100
  rpn_pre_nms_top_n_train: 2000
  rpn_post_nms_top_n_train: 1000
  rpn_post_nms_top_n_test: 500
  rpn_fg_iou_thresh: 0.7
  rpn_bg_iou_thresh: 0.3
  box_fg_iou_thresh: 0.6
  box_bg_iou_thresh: 0.3
  box_batch_size_per_image: 512
  box_positive_fraction: 0.35
  anchor_sizes: [[4, 8, 16, 32, 64, 96, 128, 256]]
  anchor_ratios: [[0.5, 0.75, 1.0, 1.5, 2.0]]

# Data configuration
data:
  train_dir: "data/new_train"
  val_dir: "data/new_val"
  train_annotations: "annotations/new_train.json"
  val_annotations: "annotations/new_val.json"
  num_workers: 0
  pin_memory: false
  persistent_workers: false

# Resource configuration
resources:
  memory_config: "max_split_size_mb:32"
  cuda_benchmark: true